# GoReleaser configuration for AIStor Snapshot
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Note: Tests are disabled until all commands are migrated
    # Run tests before building
    # - go test ./...

builds:
  - id: aissnap
    binary: aissnap
    main: ./cmd/aissnap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # Build flags to include version information
    ldflags:
      - -s -w
      - -X github.com/pavelanni/aistor-snapshot/cmd.Version={{.Version}}
      - -X github.com/pavelanni/aistor-snapshot/cmd.Commit={{.Commit}}
      - -X github.com/pavelanni/aistor-snapshot/cmd.BuildDate={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Include additional files in the archive
    files:
      - README.md
      - LICENSE*
      - MIGRATION_PATTERN.md

nfpms:
  - id: packages
    package_name: aissnap
    vendor: Pavel Anni
    homepage: https://github.com/pavelanni/aistor-snapshot
    maintainer: Pavel Anni <pavelanni@gmail.com>
    description: MinIO cluster configuration management tool
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    # Package dependencies
    dependencies: []
    # Files to include in the package
    contents:
      - src: README.md
        dst: /usr/share/doc/aissnap/README.md
      - src: MIGRATION_PATTERN.md
        dst: /usr/share/doc/aissnap/MIGRATION_PATTERN.md
    # RPM-specific configuration
    rpm:
      group: Applications/System
      compression: lzma
    # DEB-specific configuration
    deb:
      compression: xz

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - 'typo'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: pavelanni
    name: aistor-snapshot
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## AIStor Snapshot {{.Version}}

    MinIO cluster configuration management tool for capturing, analyzing, and managing cluster state.

    ### Installation

    #### Homebrew (macOS)
    ```bash
    brew install pavelanni/tap/aissnap
    ```

    #### Linux (DEB)
    ```bash
    wget https://github.com/pavelanni/aistor-snapshot/releases/download/{{.Tag}}/aissnap_{{.Version}}_Linux_x86_64.deb
    sudo dpkg -i aissnap_{{.Version}}_Linux_x86_64.deb
    ```

    #### Linux (RPM)
    ```bash
    wget https://github.com/pavelanni/aistor-snapshot/releases/download/{{.Tag}}/aissnap_{{.Version}}_Linux_x86_64.rpm
    sudo rpm -i aissnap_{{.Version}}_Linux_x86_64.rpm
    ```

    #### Manual Installation
    Download the appropriate archive for your platform from the assets below and extract the binary to your PATH.

  footer: |
    **Full Changelog**: https://github.com/pavelanni/aistor-snapshot/compare/{{.PreviousTag}}...{{.Tag}}

    ---
    For support and questions, please open an issue on GitHub.

# Homebrew tap configuration (optional)
# Note: You need to create a homebrew-tap repository first at:
# https://github.com/pavelanni/homebrew-tap
# Uncomment this section when you're ready to publish to Homebrew
# brews:
#   - name: aissnap
#     repository:
#       owner: pavelanni
#       name: homebrew-tap
#     directory: Formula
#     homepage: https://github.com/pavelanni/aistor-snapshot
#     description: MinIO cluster configuration management tool
#     license: Apache-2.0
#     test: |
#       system "#{bin}/aissnap --version"
#     install: |
#       bin.install "aissnap"

# Docker images (optional - uncomment if you want Docker images)
# dockers:
#   - image_templates:
#       - "pavelanni/aissnap:{{ .Version }}-amd64"
#       - "pavelanni/aissnap:latest-amd64"
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#     dockerfile: Dockerfile

# Additional metadata
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
